# Generated by Django 3.2.9 on 2021-11-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20211102_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('ECO', 'ECONOMY'), ('FAM', 'FAMILY'), ('BUS', 'BUSINESS')], max_length=3),
        ),
    ]
