# Generated by Django 3.2.9 on 2021-11-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
