# Generated by Django 3.2.9 on 2021-11-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='pix.jpg', upload_to='products'),
        ),
    ]
