# Generated by Django 3.2.9 on 2021-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_order',
            field=models.BooleanField(default=False),
        ),
    ]
