# Generated by Django 3.2.9 on 2021-11-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_no',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
