# Generated by Django 3.2.9 on 2021-11-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_booking_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max',
            new_name='max_order',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='min',
            new_name='min_order',
        ),
    ]
