# Generated by Django 3.2.9 on 2021-11-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20211119_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
