# Generated by Django 3.2.9 on 2021-11-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20211119_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
