# Generated by Django 3.2.9 on 2021-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20211119_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
