# Generated by Django 3.2.9 on 2021-11-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0018_auto_20211126_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
