# Generated by Django 4.0.2 on 2022-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
