# Generated by Django 4.0.2 on 2022-02-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_remove_booking_quantity_booking_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
    ]
