# Generated by Django 4.0.2 on 2022-02-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_remove_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='biz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='eco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='fam',
            field=models.BooleanField(default=False),
        ),
    ]
