# Generated by Django 4.0.2 on 2022-02-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_alter_room_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
    ]
